name: Deploy to Cloud Run

env:
  SERVICE_NAME: custom-nextapp-service
  PROJECT_ID: app-web-467210
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/app-web-467210/nextjs-app/custom-nextapp-service

on:
  push:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate unique tag
        id: tag
        run: |
          TAG=${GITHUB_SHA:0:7}
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:${{ steps.tag.outputs.TAG }} -f Dockerfile.prod .
          docker push ${{ env.DOCKER_IMAGE_URL }}:${{ steps.tag.outputs.TAG }}

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying service $SERVICE_NAME"
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --update-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }}
